# This is built for Docker Compose 1.6 and Docker 1.10+
version: "2"

services:
  # Maybe eventually will build my own zookeeper
  # but not now...
  zookeeper:
    image: jplock/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  nimbus:
    image: undeadops/storm-nimbus
    links:
      - zookeeper:zk
    ports:
      - "6627:6627"
      - "3772:3772"
      - "3773:3773"
    depends_on:
      - zookeeper

  supervisor:
    image: undeadops/storm-supervisor
    ports:
      - "6701:6701"
      - "6702:6702"
      - "6703:6703"
      - "6704:6704"
      - "8000:8000"
    links:
      - nimbus:nimbus
      - zookeeper:zk
    depends_on:
      - zookeeper
      - nimbus

  ui:
    image: undeadops/storm-ui
    links:
      - nimbus:nimbus
      - zookeeper:zk
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - nimbus
