# This is built for Docker Compose 1.6 and Docker 1.10+
version: "2"

services:
  # Maybe eventually will build my own zookeeper
  # but not now...
  zookeeper:
    image: jplock/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  nimbus:
    image: undeadops/storm-nimbus
    ports:
      - "49773:3773"
      - "49772:3772"
      - "49627:6627"
    links:
      - zookeeper:zk

  supervisor:
    image: undeadops/storm-supervisor
    ports:
      - "8000"
    links:
      - nimbus:nimbus
      - zookeeper:zk
      
  ui:
    image: undeadops/storm-ui
    ports:
      - "49080:8080"
    links:
      - nimbus:nimbus
      - zookeeper:zk
